-- Migration: 20260105_120000_messages_reply_idempotency
-- Purpose:
-- Add a dedicated column for assistant reply idempotency and enforce at-most-once
-- assistant reply per (conversation_id, triggering user message).
--
-- Design:
-- - `triggered_by_message_id` is set ONLY on assistant *reply* messages generated by
--   assistant-chat-reply (meta.ai.provider is present).
-- - Other assistant messages (rate-limit notices, action-result followups, etc.)
--   MUST keep this column NULL to avoid collisions.

begin;

-- 1) Add the column.
alter table if exists public.messages
  add column if not exists triggered_by_message_id uuid;

-- 2) Backfill from legacy JSON metadata, but ONLY for assistant replies.
--    (We detect replies by presence of meta.ai.provider, which is set by assistant-chat-reply.)
update public.messages
set triggered_by_message_id = (meta->'triggeredBy'->>'userMessageId')::uuid
where triggered_by_message_id is null
  and (meta->'ai'->>'provider') is not null
  and (meta->'triggeredBy'->>'userMessageId') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';


-- 2.5) If historical duplicates exist, keep the newest assistant reply and null out the rest
--      so the UNIQUE index can be created safely.
with ranked as (
  select id,
         row_number() over (partition by conversation_id, triggered_by_message_id order by created_at desc, id desc) as rn
  from public.messages
  where triggered_by_message_id is not null
    and (meta->'ai'->>'provider') is not null
)
update public.messages m
set triggered_by_message_id = null
from ranked r
where m.id = r.id
  and r.rn > 1;

-- 3) Fast lookup index.
create index if not exists idx_messages_conversation_triggered_by_message_id
  on public.messages (conversation_id, triggered_by_message_id)
  where triggered_by_message_id is not null;

-- 4) Enforce at-most-once assistant reply per triggering user message.
--    (We don't include user_id in the index because ONLY assistant replies populate the column.)
create unique index if not exists ux_messages_reply_idempotency
  on public.messages (conversation_id, triggered_by_message_id)
  where triggered_by_message_id is not null;

commit;
